# Site settings
title: Code Greg
header-img: img/home-bg.png
email: gregbenj@gmail.com
copyright_name: gb23
description: > # this means to ignore newlines until "baseurl:"
  Please be advised: we have a Code Greg unfolding.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  gb23
learn_profile: gb23
email_username: gregbenj@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
